- name: Grant Cosmos DB Data Contributor to UAMI (payments DB)
  ansible.builtin.include_role:
    name: azurefactory.databases.create_cosmos_db_role_assignment_201
  vars:
    cloud_element: "{{ azf.resources.cosmosdb_1 }}"
    settings:
      role: "Cosmos DB Built-in Data Contributor"
      scope: "/dbs/payments"  
    dependency:
      spn:
        settings:
          object_id: "{{ uami_out.principalId }}"


  - name: Test Cosmos RBAC assignment
  azurefactory.core.run_az_001:
    cmd: >
      cosmosdb sql role assignment list
      --account-name {{ azf.resources.cosmosdb_1.name }}
      --resource-group {{ azf.resources.cosmosdb_1.group_name }}
      --query "[?principalId=='{{ uami_out.principalId }}' && scope=='/dbs/payments']"
      --output json
  register: cosmos_rbac_test

- name: Assert UAMI has Cosmos DB role
  ansible.builtin.assert:
    that:
      - cosmos_rbac_test.json | length > 0
    fail_msg: " UAMI RBAC assignment could not find in scope /dbs/payments"
    success_msg: "For UAMI found RBAC assignment in scope /dbs/payments"

